
site_name: DSG_LIB
# Project information
site_description: 'Common functions for Python applications. This is to increase reusability and limit rewritting the same functions in multiple applications. It also allows for defects to be addressed quickly and then be propigated across applications.'
site_author: 'Mike Ryan'
# site_url: 'https://squidfunk.github.io/mkdocs-material/'
# Repository
repo_name: 'devsetgo/dsg_lib'
repo_url: 'https://github.com/devsetgo/dsg_lib'

# Copyright
copyright: 'Copyright &copy; 2016 - 2023 Mike Ryan'

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quickstart.md'
    - Common Functions:
      - Logging: 'functions/logging.md'
      - File Functions: 'functions/file_functions.md'
      - Folder Functions: 'functions/folder_functions.md'
      - RegEx Functions: 'functions/regex.md'
      - Calendar Functions: 'functions/calendar_functions.md'
    - FastAPI Functions:
      - HTTP Codes: 'endpoints/http_codes.md'
      - System Health: 'endpoints/system_health_endpoints.md'
    - Database Functions:
      - Database Configuration: 'database/database_configuration.md'
      - Async Database Setup: 'database/async_database_setup.md'
      - Database Operations: 'database/database_operations.md'
      - Base Schema: 'database/base_schema.md'
    - Recipes:
      - FastAPI: 'recipes/fastapi.md'
      - Async Database: 'recipes/asyncDatabase.md'
      - Logging: 'recipes/loggingExample.md'
      - Patterns: 'recipes/patterns.md'
    - About:
      - Contributing: 'contribute.md'
    - Release Notes: release-notes.md
# Theme
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
    - navigation.top
  name: 'material'
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  language: en
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [dsg_lib, examples]
          options:
            heading_level: 2
            docstring_style: google
            show_source: true
            show_root_heading: True
            show_symbol_type_heading: True
            show_docstring_examples: True
            show_submodules: True


# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/devsetgo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_devsetgo
