
site_name: 'DevSetGo Library'
# Project information
site_description: 'Common functions for Python applications. This is to increase reusability and limit rewritting the same functions in multiple applications. It also allows for defects to be addressed quickly and then be propigated across applications.'
site_author: 'Mike Ryan'
# site_url: 'https://squidfunk.github.io/mkdocs-material/'
# Repository
repo_name: 'devsetgo/dsg_lib'
repo_url: 'https://github.com/devsetgo/dsg_lib'

# Copyright
copyright: 'Copyright &copy; 2016 - 2024 Mike Ryan'

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quickstart.md'
    - Common Functions:
      - Logging: 'common_functions/logging.md'
      - File Functions: 'common_functions/file_functions.md'
      - Folder Functions: 'common_functions/folder_functions.md'
      - RegEx Functions: 'common_functions/regex.md'
      - Calendar Functions: 'common_functions/calendar_functions.md'
    - FastAPI Functions:
      - HTTP Codes: 'fastapi/http_codes.md'
      - System Health: 'fastapi/system_health_endpoints.md'
    - Database Functions:
      - Base Schema: 'database/base_schema.md'
      - Database Configuration: 'database/database_configuration.md'
      - Async Database Setup: 'database/async_database_setup.md'
      - Database Operations: 'database/database_operations.md'

    - Recipes:
      - FastAPI: 'recipes/fastapi.md'
      - Async Database: 'recipes/asyncDatabase.md'
      - Logging: 'recipes/loggingExample.md'
      - Patterns: 'recipes/patterns.md'
      - EmailValidation: 'recipes/emailValidation.md'
    - About:
      - About: 'about.md'
      - Contributing: 'contribute.md'
    - Release Notes: release-notes.md
# Theme
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
    - navigation.top
  name: 'material'
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  language: en
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 2
            docstring_style: google
            show_source: true
            show_root_heading: True
            show_symbol_type_heading: True
            show_docstring_examples: True
            show_submodules: True
  # this has to be last
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Site'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      # cover_page_template: ""
      # path_to_pdf: ""
      include_css: true
      enabled: true

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/devsetgo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_devsetgo
