
site_name: DSG_LIB
# Project information
site_name: 'DSG_LIB'
site_description: 'Common functions for Python applications. This is to increase reusability and limit rewritting the same functions in multiple applications. It also allows for defects to be addressed quickly and then be propigated across applications.'
site_author: 'Mike Ryan'
# site_url: 'https://squidfunk.github.io/mkdocs-material/'
# Repository
repo_name: 'devsetgo/dsg_lib'
repo_url: 'https://github.com/devsetgo/dsg_lib'

# Copyright
copyright: 'Copyright &copy; 2016 - 2021 Mike Ryan'

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quickstart.md'
    - Common Functions:
      - Logging: 'common/logging.md'
      - File Functions: 'common/file_functions.md'
      - Folder Functions: 'common/folder_functions.md'
      - RegEx Functions: 'common/regex.md'
      - Calendar Functions: 'common/calendar_functions.md'
    - FastAPI Functions:
      - HTTP Codes: 'fastapi/http_codes.md'
      - System Health: 'fastapi/system_health_endpoints.md'
      - Full Example: 'fastapi/full_library_example.md'
    - Database Functions:
      - Database Configuration: 'database/database_configuration.md'
      - Async Database Setup: 'database/async_database_setup.md'
      - Database Operations: 'database/database_operations.md'
      - Base Schema: 'database/base_schema.md'
      - Example: 'database/example.md'
    - About:
      - Contributing: 'contribute.md'
    - Release Notes: release-notes.md
# Theme
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
    - navigation.top
  name: 'material'
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  language: en
  plugins:
    - search

  # font:
  #   text: 'Roboto'
  #   code: 'Roboto Mono'
  # logo:
  #   icon:
  #     repo: fontawesome/solid/people-carry
  # language: 'en'
  # plugins:
  # - search

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/devsetgo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_devsetgo
