name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate changelog
        run: python3 scripts/changelog.py

      - name: Build MkDocs site
        run: mkdocs build

      - name: Copy README to docs/index.md
        run: cp README.md docs/index.md

      - name: Copy CONTRIBUTING to docs/contribute.md
        run: cp CONTRIBUTING.md docs/contribute.md

      - name: Copy CHANGELOG to docs/release-notes.md
        run: cp CHANGELOG.md docs/release-notes.md

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# name: Publish docs via GitHub Pages
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Deploy docs
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout main
#         uses: actions/checkout@v2

#       - name: Deploy docs
#         uses: mhausenblas/mkdocs-deploy-gh-pages@master
#         # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           CUSTOM_DOMAIN: optionaldomain.com
#           CONFIG_FILE: folder/mkdocs.yml
#           EXTRA_PACKAGES: build-base
#           # GITHUB_DOMAIN: github.myenterprise.com
#           REQUIREMENTS: folder/requirements.txt
