name: Latest Changes

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tiangolo/latest-changes@0.2.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        latest_changes_file: docs/release-notes.md
        latest_changes_header: '# Release Notes'
        template_file: ./.github/workflows/release-notes.jinja2
        # The next release will start with this RegEx, for example "## 0.2.0"
        end_regex: '^## '
        debug_logs: true
        # Here we use a yaml multiline string to pass a JSON array of JSON objects in a more readable way
        # In these case we use the same default labels and the same header titles, but the headers use 3 hash symbols instead of the default of 4
        # We also add a custom last label "egg" for PRs with easter eggs.
        labels: >
          [
            {"label": "breaking", "header": "Breaking Changes"},
            {"label": "security", "header": "Security Fixes"},
            {"label": "feature", "header": "Features"},
            {"label": "bug", "header": "Fixes"},
            {"label": "refactor", "header": "Refactors"},
            {"label": "upgrade", "header": "Upgrades"},
            {"label": "docs", "header": "Docs"},
            {"label": "lang-all", "header": "Translations"},
            {"label": "internal", "header": "Internal"},
            {"label": "egg", "header": "Easter Eggs"}
          ]
        # This will be added to the start of each label's header and
        # will be used to detect existing label headers
        label_header_prefix: '### '

